mutation CheckInsuranceAndRequestVehicles ($address: InputAddress!, $assessee: InputAssessee!) {
    assess {
        id
        checkInsurance (assessee: $assessee, address: $address) {
            policies {
                started
            }
        }
        requestVehicles (assessee: $assessee, address: $address) {
            started
        }
    }
}